services:
  postgres:
    container_name: inbox-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: inbox
      POSTGRES_PASSWORD: inbox
      POSTGRES_DB: inbox
    ports:
      - "5432:5432"
    volumes:
      - ./internal/infrastructure/db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inbox -d inbox"]
      interval: 5s
      timeout: 3s
      retries: 20
